-- ============================================================================
-- Nexora catalog seed (generated from src/data/mockData.ts)
-- Safe to re-run: uses ON CONFLICT ... DO UPDATE.
-- ============================================================================

insert into public.salons (id, name, area, city, distance_km, rating, review_count, verified, is_new, image, gallery, starting_price, tags, gender_category, address, hours, description) values
  ('aura-premium', 'Aura Premium Studio', '100ft Road', 'Bangalore', 1.2, 4.9, 120, true, false, 'https://lh3.googleusercontent.com/aida-public/AB6AXuAXNrkRfI9y_os1hhcj59fy20hKE4l0QqGUNQVn-XxClnWXAHhxsUq9StaxNDW-gVTqgRCTs4CRcDREHkDRl3O281WKov_60JM-vqbkQx2HFWfO7hqLgolrxEBjj4YuPr8wtWTvV7UvBSHcdo3tRzO_LrCzSCVWB6G_buJc_4YPh8LM_76wAGfy-QauOBGWykpt8KUDauq9kcOnmuvYaFU9Er-tKCssEugNxpC4_9MFMrErejr4RxpAFvlV13B_Jrs16yTwJhZbPFo', '["https://lh3.googleusercontent.com/aida-public/AB6AXuAXNrkRfI9y_os1hhcj59fy20hKE4l0QqGUNQVn-XxClnWXAHhxsUq9StaxNDW-gVTqgRCTs4CRcDREHkDRl3O281WKov_60JM-vqbkQx2HFWfO7hqLgolrxEBjj4YuPr8wtWTvV7UvBSHcdo3tRzO_LrCzSCVWB6G_buJc_4YPh8LM_76wAGfy-QauOBGWykpt8KUDauq9kcOnmuvYaFU9Er-tKCssEugNxpC4_9MFMrErejr4RxpAFvlV13B_Jrs16yTwJhZbPFo","https://lh3.googleusercontent.com/aida-public/AB6AXuBU5ioD8ECJwIjxf7nL4GFiYyZkC5KS9Tg8KviIMZ4CQku5WLJ80Kw5gHfDNX25-h8BpHG7ERQfPqwDCPMBlrvja3Xupvm6LKWDVV41_kohsb0cvPH_cv51wS_UH7nIDqMz0FBSJOBjzLyOLHKhiZKO5v944i_9rLFRn4mKrb2WhYszYN2NVkwnK2Nb5RfeQVqjlr-qlwQ3_MJshmlX8Jh_40ZJZJEhNRF4GFrlbKvBt5hetyLuYpPLKfV6QZKXHnjN4Xp0viG_rmE","https://lh3.googleusercontent.com/aida-public/AB6AXuBKjqHS__8pKWlHQ0Of3E1en-fZ_uPaluRnj_EcHI8HW7-6R2LvSOhQcijKHb2JQYglet-oxJ8Hu_RwNTv8SFK5ceJ8eBir2yMm1MhgA_laUQyPGxY6cz6YWIhOMFGE7kud32k81Nr9EIrexOLPo0oTRew5qiW7SWl7CTwTs9hWSTXArKuKJee_7o1oqJ6jz22o-DYlUb3CAsOrW-N3ZvBwHOvAppEv2ZTneVEaVI76gT32y-yGNASksxSfpP07R3nBV3etgqePX2Y"]'::jsonb, 899, '["Hair Color","Balayage","Hair Spa"]'::jsonb, 'Unisex', '42, 100ft Road, Indiranagar, Bangalore 560038', '10:00 AM - 8:30 PM', 'Aura Premium Studio offers an ultra-luxurious hair and scalp experience. Featuring custom Balayage, organic Kerastase rituals, and tailored precision haircuts.'),
  ('glam-room', 'The Glam Room', 'Bandra West', 'Mumbai', 1.2, 4.9, 128, true, false, 'https://lh3.googleusercontent.com/aida-public/AB6AXuBU5ioD8ECJwIjxf7nL4GFiYyZkC5KS9Tg8KviIMZ4CQku5WLJ80Kw5gHfDNX25-h8BpHG7ERQfPqwDCPMBlrvja3Xupvm6LKWDVV41_kohsb0cvPH_cv51wS_UH7nIDqMz0FBSJOBjzLyOLHKhiZKO5v944i_9rLFRn4mKrb2WhYszYN2NVkwnK2Nb5RfeQVqjlr-qlwQ3_MJshmlX8Jh_40ZJZJEhNRF4GFrlbKvBt5hetyLuYpPLKfV6QZKXHnjN4Xp0viG_rmE', '["https://lh3.googleusercontent.com/aida-public/AB6AXuBU5ioD8ECJwIjxf7nL4GFiYyZkC5KS9Tg8KviIMZ4CQku5WLJ80Kw5gHfDNX25-h8BpHG7ERQfPqwDCPMBlrvja3Xupvm6LKWDVV41_kohsb0cvPH_cv51wS_UH7nIDqMz0FBSJOBjzLyOLHKhiZKO5v944i_9rLFRn4mKrb2WhYszYN2NVkwnK2Nb5RfeQVqjlr-qlwQ3_MJshmlX8Jh_40ZJZJEhNRF4GFrlbKvBt5hetyLuYpPLKfV6QZKXHnjN4Xp0viG_rmE","https://lh3.googleusercontent.com/aida-public/AB6AXuAXNrkRfI9y_os1hhcj59fy20hKE4l0QqGUNQVn-XxClnWXAHhxsUq9StaxNDW-gVTqgRCTs4CRcDREHkDRl3O281WKov_60JM-vqbkQx2HFWfO7hqLgolrxEBjj4YuPr8wtWTvV7UvBSHcdo3tRzO_LrCzSCVWB6G_buJc_4YPh8LM_76wAGfy-QauOBGWykpt8KUDauq9kcOnmuvYaFU9Er-tKCssEugNxpC4_9MFMrErejr4RxpAFvlV13B_Jrs16yTwJhZbPFo","https://lh3.googleusercontent.com/aida-public/AB6AXuBqhV0t5j__2UFAE_pYAATwrVVeuEo_35VQz8aItegXSp285ZOGugHYZnkRVTrRUKgMzzOLNjuuAKFwUaFUn8Ko1MSDyJG59ktfQGxwQ57XtjnikoWEEtEIq2zBFLglXZk2SdoSnnNVXm7iW7W446ICYYFJu-Op0WaK4UfUULDd_JcuGnb5N-4eUFDkFSw7-JcFpZ4NKsyRaaENuf2NYPKhBsQ-d06_dqmhcRFdfxzC3l1t3ADz_AiGTfMe-QKdNkn4QltKcX6L6Xc"]'::jsonb, 800, '["Hair Styling","Creative Color","Keratin Spa"]'::jsonb, 'Unisex', '14/A Waterfield Road, Bandra West, Mumbai, Maharashtra 400050', '10:00 AM - 8:00 PM', 'The Glam Room is a premium sanctuary for modern beauty. We specialize in bespoke haircuts, advanced coloring techniques, and rejuvenating skin treatments using top-tier international products.'),
  ('lumiere-studio', 'Lumière Studio', 'Bandra West', 'Mumbai', 1.2, 4.8, 96, true, false, 'https://lh3.googleusercontent.com/aida-public/AB6AXuBKjqHS__8pKWlHQ0Of3E1en-fZ_uPaluRnj_EcHI8HW7-6R2LvSOhQcijKHb2JQYglet-oxJ8Hu_RwNTv8SFK5ceJ8eBir2yMm1MhgA_laUQyPGxY6cz6YWIhOMFGE7kud32k81Nr9EIrexOLPo0oTRew5qiW7SWl7CTwTs9hWSTXArKuKJee_7o1oqJ6jz22o-DYlUb3CAsOrW-N3ZvBwHOvAppEv2ZTneVEaVI76gT32y-yGNASksxSfpP07R3nBV3etgqePX2Y', '["https://lh3.googleusercontent.com/aida-public/AB6AXuBKjqHS__8pKWlHQ0Of3E1en-fZ_uPaluRnj_EcHI8HW7-6R2LvSOhQcijKHb2JQYglet-oxJ8Hu_RwNTv8SFK5ceJ8eBir2yMm1MhgA_laUQyPGxY6cz6YWIhOMFGE7kud32k81Nr9EIrexOLPo0oTRew5qiW7SWl7CTwTs9hWSTXArKuKJee_7o1oqJ6jz22o-DYlUb3CAsOrW-N3ZvBwHOvAppEv2ZTneVEaVI76gT32y-yGNASksxSfpP07R3nBV3etgqePX2Y"]'::jsonb, 1500, '["Unisex","Kerastase Spa","Moroccan Oil"]'::jsonb, 'Unisex', '88, Turner Road, Bandra West, Mumbai, Maharashtra 400050', '10:00 AM - 9:00 PM', 'French minimalist aesthetic studio offering bespoke Moroccan Oil massages, advanced scalp rejuvenation, and couture hair transformations.'),
  ('derma-glow', 'DermaGlow Clinic', 'CMH Road', 'Bangalore', 2.5, 4.7, 45, true, true, 'https://lh3.googleusercontent.com/aida-public/AB6AXuBqhV0t5j__2UFAE_pYAATwrVVeuEo_35VQz8aItegXSp285ZOGugHYZnkRVTrRUKgMzzOLNjuuAKFwUaFUn8Ko1MSDyJG59ktfQGxwQ57XtjnikoWEEtEIq2zBFLglXZk2SdoSnnNVXm7iW7W446ICYYFJu-Op0WaK4UfUULDd_JcuGnb5N-4eUFDkFSw7-JcFpZ4NKsyRaaENuf2NYPKhBsQ-d06_dqmhcRFdfxzC3l1t3ADz_AiGTfMe-QKdNkn4QltKcX6L6Xc', '["https://lh3.googleusercontent.com/aida-public/AB6AXuBqhV0t5j__2UFAE_pYAATwrVVeuEo_35VQz8aItegXSp285ZOGugHYZnkRVTrRUKgMzzOLNjuuAKFwUaFUn8Ko1MSDyJG59ktfQGxwQ57XtjnikoWEEtEIq2zBFLglXZk2SdoSnnNVXm7iW7W446ICYYFJu-Op0WaK4UfUULDd_JcuGnb5N-4eUFDkFSw7-JcFpZ4NKsyRaaENuf2NYPKhBsQ-d06_dqmhcRFdfxzC3l1t3ADz_AiGTfMe-QKdNkn4QltKcX6L6Xc"]'::jsonb, 1499, '["Hydrafacial","Peels","Dermatology"]'::jsonb, 'Unisex', '102, CMH Road, Indiranagar, Bangalore 560038', '10:30 AM - 7:30 PM', 'Clinical skin therapy studio led by certified dermatologists. Hydro-dermabrasion, light therapy, and anti-aging peel solutions.'),
  ('hive-salon', 'The Hive Salon', 'Khar West', 'Mumbai', 2.5, 4.6, 78, false, false, 'https://lh3.googleusercontent.com/aida-public/AB6AXuCRM-yy6OnbhOFhZAmgbO5Bm_QrPNOwqdj9ZcphuYvSUbw8Mib0fdO6cdWjt-o80qBuG_zE0iRFTIvBhPpbR85jKoWtVyGDo-5CJSjrMUe6RT0qENN-sc6DPKe8ClliS4oUM9j18gEf6WCkg6KTkEht-x5lqRZP4-5MqysbqXLlLuYp7Sd-RYTbYMQcyAjhnhTGbeI7MImTskPu9qZ4FKBsrczSbLIUZ7_UdpK3kNX4VSiqefXp_Jj88KN-29TzfOIV1LH9L3-_0zg', '["https://lh3.googleusercontent.com/aida-public/AB6AXuCRM-yy6OnbhOFhZAmgbO5Bm_QrPNOwqdj9ZcphuYvSUbw8Mib0fdO6cdWjt-o80qBuG_zE0iRFTIvBhPpbR85jKoWtVyGDo-5CJSjrMUe6RT0qENN-sc6DPKe8ClliS4oUM9j18gEf6WCkg6KTkEht-x5lqRZP4-5MqysbqXLlLuYp7Sd-RYTbYMQcyAjhnhTGbeI7MImTskPu9qZ4FKBsrczSbLIUZ7_UdpK3kNX4VSiqefXp_Jj88KN-29TzfOIV1LH9L3-_0zg"]'::jsonb, 1200, '["Women Only","Olaplex Spa","Aromatherapy"]'::jsonb, 'Women Only', '5th Road, Khar West, Mumbai, Maharashtra 400052', '11:00 AM - 8:00 PM', 'An eco-friendly women-only boutique salon surrounded by lush botanical elements. Organic color lines and Olaplex hair bonding.')
on conflict (id) do update set
  name = excluded.name, area = excluded.area, city = excluded.city,
  distance_km = excluded.distance_km, rating = excluded.rating,
  review_count = excluded.review_count, verified = excluded.verified,
  is_new = excluded.is_new, image = excluded.image, gallery = excluded.gallery,
  starting_price = excluded.starting_price, tags = excluded.tags,
  gender_category = excluded.gender_category, address = excluded.address,
  hours = excluded.hours, description = excluded.description;

insert into public.services (id, salon_id, name, duration_minutes, price, category, description, sort_order) values
  ('aura-premium:a1', 'aura-premium', 'Woman''s Haircut & Blowdry', 45, 899, 'Hair Styling', 'Precision hair trim with customized styling and signature blowdry.', 0),
  ('aura-premium:a2', 'aura-premium', 'Balayage & Toning', 120, 3499, 'Hair Styling', 'Hand-painted sun-kissed highlights with premium gloss toner.', 1),
  ('aura-premium:a3', 'aura-premium', 'Kerastase Elixir Hair Spa', 60, 1899, 'Hair Spa', 'Deep nourishing ritual for smooth, lustrous locks.', 2),
  ('aura-premium:a4', 'aura-premium', 'HydraGlow Facial Treatment', 60, 2100, 'Skin Care', 'Infusion of hyaluronic serum for radiant glass skin.', 3),
  ('glam-room:g1', 'glam-room', 'Woman''s Haircut', 45, 800, 'Hair Styling', 'Senior Stylist precision haircut, wash and customized styling.', 0),
  ('glam-room:g2', 'glam-room', 'Creative Coloring', 120, 2500, 'Hair Styling', 'Vibrant highlight gloss or custom dimensional color tint. Includes wash.', 1),
  ('glam-room:g3', 'glam-room', 'Keratin Treatment', 90, 4200, 'Spa & Care', 'Intensive smoothing treatment using premium formaldehyde-free keratin.', 2),
  ('glam-room:g4', 'glam-room', 'Signature Gel Manicure', 45, 1200, 'Nails', 'Long-lasting high-shine polish with cuticle detox massage.', 3),
  ('lumiere-studio:l1', 'lumiere-studio', 'Kerastase Hair Spa', 60, 1500, 'Hair Spa', 'Intensive scalp detox and strand smoothing.', 0),
  ('lumiere-studio:l2', 'lumiere-studio', 'Classic Manicure', 30, 650, 'Nails', 'Cuticle shaping, gentle scrub, and nail polish application.', 1),
  ('lumiere-studio:l3', 'lumiere-studio', 'Moroccan Oil Treatment', 75, 2200, 'Hair Spa', 'Pure argan oil massage and steam therapy.', 2),
  ('derma-glow:d1', 'derma-glow', 'Clinical Hydrafacial 3D', 60, 2999, 'Skin Care', 'Pore extraction, diamond tip abrasion, hyaluronic serum injection.', 0),
  ('derma-glow:d2', 'derma-glow', 'Radiance Chemical Peel', 45, 1499, 'Skin Care', 'Gentle glycolic rejuvenation for instant brightness.', 1),
  ('hive-salon:h1', 'hive-salon', 'Olaplex Repair Spa', 60, 1200, 'Hair Spa', 'Bond building system to restore damaged protein bonds.', 0),
  ('hive-salon:h2', 'hive-salon', 'Aromatherapy Facial', 50, 1600, 'Skin Care', 'Essential oils massage for stress relief and skin hydration.', 1)
on conflict (id) do update set
  name = excluded.name, duration_minutes = excluded.duration_minutes,
  price = excluded.price, category = excluded.category,
  description = excluded.description, sort_order = excluded.sort_order;

insert into public.staff (id, salon_id, name, role, rating, reviews_count, avatar, sort_order) values
  ('aura-premium:s1', 'aura-premium', 'Maya S.', 'Senior Stylist', 4.9, 84, 'https://lh3.googleusercontent.com/aida-public/AB6AXuB6FnEPu-SL4wCFVKcdUT8T3HAr4WTtQffHbnb-a1Q_KHmwlXmuuMexI_oX7VO3Ck7qecdPxZscnfPyNFROadrFDvlkX2aKpGC7DKv8u_kCOn8d2MGCISl3rqUL79jDHNAaMeiBfwgEUSzl-uZoz702Y0_08nr4fJCuUBFEAasK6fvfIalsfNsECYrq-GqF_jzTRNgR4lOYUXXnfcExQ5qPrfu7Tw6Sle-tPP-le3KXO-hb9dwZ-x-2wkRrIieKF0Y75ikYZ-xFPME', 0),
  ('aura-premium:s2', 'aura-premium', 'Rahul K.', 'Color Specialist', 4.8, 62, 'https://lh3.googleusercontent.com/aida-public/AB6AXuAym-1XqNvvUES_juaNcLK1p8qid6RxJWHmLyEsIlb7AZSTPL3DCcTaY--lrpsKfwZwtjvl2FDo7LyVmLuDZb5KGoPI2DvOGefWFzVJnsIXTM2NkLwCvN_xGTXmI3_23Le-KpVYYx4qmB4kzK9QGaBpL0uNx2cigDOD6i19c0NbGXmLIMKy3m7bC9xhY50Odkqojhl7HF4nT9FrV_K_3UJKBBfiUTYnIcThOzvvmaz4DyrB8m0nL0W3-kL4DbP7Oyz_grSdxlUlWHQ', 1),
  ('aura-premium:s3', 'aura-premium', 'Zara M.', 'Esthetician', 5, 120, 'https://lh3.googleusercontent.com/aida-public/AB6AXuB9RAhukgBLye8hQOojgrb3bjsb6PQ_GhdMufuidFvlJqxVZ_xINH0Fdc1_s8l0aKXMACAyJMrQquxZKVQXPbcPnysxo2AAatGH3nEL1rVhgI_0bjqpB9KoTtaO7uJwL42BWgx9jqqZT8lTENQn-lR5HjKB-qPHz60CkRRmoz6LOby9AqVT6YTIEvV8qGyGrD_9L7ajxDuE2iRaPMw8FOg6RbQvHBxMhsSz267is5uVRucT7hdBBpbaVJ93mQq5R3csJlGGpBtEazk', 2),
  ('glam-room:s1', 'glam-room', 'Maya S.', 'Senior Stylist', 4.9, 84, 'https://lh3.googleusercontent.com/aida-public/AB6AXuB6FnEPu-SL4wCFVKcdUT8T3HAr4WTtQffHbnb-a1Q_KHmwlXmuuMexI_oX7VO3Ck7qecdPxZscnfPyNFROadrFDvlkX2aKpGC7DKv8u_kCOn8d2MGCISl3rqUL79jDHNAaMeiBfwgEUSzl-uZoz702Y0_08nr4fJCuUBFEAasK6fvfIalsfNsECYrq-GqF_jzTRNgR4lOYUXXnfcExQ5qPrfu7Tw6Sle-tPP-le3KXO-hb9dwZ-x-2wkRrIieKF0Y75ikYZ-xFPME', 0),
  ('glam-room:s2', 'glam-room', 'Rahul K.', 'Color Specialist', 4.8, 62, 'https://lh3.googleusercontent.com/aida-public/AB6AXuAym-1XqNvvUES_juaNcLK1p8qid6RxJWHmLyEsIlb7AZSTPL3DCcTaY--lrpsKfwZwtjvl2FDo7LyVmLuDZb5KGoPI2DvOGefWFzVJnsIXTM2NkLwCvN_xGTXmI3_23Le-KpVYYx4qmB4kzK9QGaBpL0uNx2cigDOD6i19c0NbGXmLIMKy3m7bC9xhY50Odkqojhl7HF4nT9FrV_K_3UJKBBfiUTYnIcThOzvvmaz4DyrB8m0nL0W3-kL4DbP7Oyz_grSdxlUlWHQ', 1),
  ('glam-room:s3', 'glam-room', 'Zara M.', 'Esthetician', 5, 120, 'https://lh3.googleusercontent.com/aida-public/AB6AXuB9RAhukgBLye8hQOojgrb3bjsb6PQ_GhdMufuidFvlJqxVZ_xINH0Fdc1_s8l0aKXMACAyJMrQquxZKVQXPbcPnysxo2AAatGH3nEL1rVhgI_0bjqpB9KoTtaO7uJwL42BWgx9jqqZT8lTENQn-lR5HjKB-qPHz60CkRRmoz6LOby9AqVT6YTIEvV8qGyGrD_9L7ajxDuE2iRaPMw8FOg6RbQvHBxMhsSz267is5uVRucT7hdBBpbaVJ93mQq5R3csJlGGpBtEazk', 2),
  ('lumiere-studio:s1', 'lumiere-studio', 'Maya S.', 'Senior Stylist', 4.9, 84, 'https://lh3.googleusercontent.com/aida-public/AB6AXuB6FnEPu-SL4wCFVKcdUT8T3HAr4WTtQffHbnb-a1Q_KHmwlXmuuMexI_oX7VO3Ck7qecdPxZscnfPyNFROadrFDvlkX2aKpGC7DKv8u_kCOn8d2MGCISl3rqUL79jDHNAaMeiBfwgEUSzl-uZoz702Y0_08nr4fJCuUBFEAasK6fvfIalsfNsECYrq-GqF_jzTRNgR4lOYUXXnfcExQ5qPrfu7Tw6Sle-tPP-le3KXO-hb9dwZ-x-2wkRrIieKF0Y75ikYZ-xFPME', 0),
  ('derma-glow:s3', 'derma-glow', 'Zara M.', 'Lead Esthetician', 5, 120, 'https://lh3.googleusercontent.com/aida-public/AB6AXuB9RAhukgBLye8hQOojgrb3bjsb6PQ_GhdMufuidFvlJqxVZ_xINH0Fdc1_s8l0aKXMACAyJMrQquxZKVQXPbcPnysxo2AAatGH3nEL1rVhgI_0bjqpB9KoTtaO7uJwL42BWgx9jqqZT8lTENQn-lR5HjKB-qPHz60CkRRmoz6LOby9AqVT6YTIEvV8qGyGrD_9L7ajxDuE2iRaPMw8FOg6RbQvHBxMhsSz267is5uVRucT7hdBBpbaVJ93mQq5R3csJlGGpBtEazk', 0),
  ('hive-salon:s1', 'hive-salon', 'Maya S.', 'Senior Stylist', 4.9, 84, 'https://lh3.googleusercontent.com/aida-public/AB6AXuB6FnEPu-SL4wCFVKcdUT8T3HAr4WTtQffHbnb-a1Q_KHmwlXmuuMexI_oX7VO3Ck7qecdPxZscnfPyNFROadrFDvlkX2aKpGC7DKv8u_kCOn8d2MGCISl3rqUL79jDHNAaMeiBfwgEUSzl-uZoz702Y0_08nr4fJCuUBFEAasK6fvfIalsfNsECYrq-GqF_jzTRNgR4lOYUXXnfcExQ5qPrfu7Tw6Sle-tPP-le3KXO-hb9dwZ-x-2wkRrIieKF0Y75ikYZ-xFPME', 0)
on conflict (id) do update set
  name = excluded.name, role = excluded.role, rating = excluded.rating,
  reviews_count = excluded.reviews_count, avatar = excluded.avatar,
  sort_order = excluded.sort_order;
